version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: asdqwe123
      MYSQL_DATABASE: laravel
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume:
